script: bundle exec rake test
language: ruby
rvm:
  - ruby-head
  - 1.9.3
  - 2.1
  - 2.2
  - 2.3

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.1-dev
